configs_base_path = '../../'
configs_shape_predictor_path = configs_base_path + 'models/shape_predictor_65_face_landmarks.dat'
configs_cnn_detector_path = configs_base_path + 'models/mmod_human_face_detector.dat'
configs_faces_folder_path = configs_base_path + 'datasets/faces/'
configs_mini_faces_folder_path = configs_base_path + 'datasets/mini_faces/'
configs_recognition_model_path = configs_base_path + 'models/dlib_face_recognition_resnet_model_v1.dat'
configs_clustering_output_folder = configs_base_path + 'output/clustering'